;-----
; Note/Usage:
; ==========
;
; - any value indicated by <!section|key!> is automatically replaced by the
;   value under (section, key) at runtime
; - parameters definde for stages must start with 'param.'
; - parameters with identical names are treated as one and the same parameter,
;   even across stages!
; - a section for a stage should start with 'stage:'
; - parameters in the format param.xy.pname can be selected with a
;   param_selector defined in the given section, example:
;
;   [section:osc]
;   param_selector = nh
;   param.nh.theta23 = 12.3
;   param.ih.theta23 = 11.7
;
;   will select param.nh.theta23 during parsing and store it as a parameter
;   named 'theta23'


;------------------------------------------------------------------------------
; Settings directly affecting or handled by the template maker
;------------------------------------------------------------------------------

[pipeline]

; define order of stages to be excecuted one after another, and specify the
; service to use for each of them as stage1:serviceA, stage2:serviceB, ...
order = mc:gpu
;sys:ployfits

;------------------------------------------------------------------------------
; Binning definitions, linked back to from stage definitions
;------------------------------------------------------------------------------

[binning]

true_allsky.order = true_coszen, true_energy
true_allsky.true_energy = {'num_bins':40, 'is_log':True, 'domain':[1,80] * units.GeV, 'tex': r'$E_{\rm true}$'}
true_allsky.true_coszen = {'num_bins':40, 'is_lin':True, 'domain':[-1,1], 'tex':r'$\cos\,\theta_{Z,{\rm true}}$'}

true_nutaufine.order = true_coszen, true_energy
true_nutaufine.true_energy = {'num_bins':150, 'is_log':True, 'domain':[2.3,180] * units.GeV, 'tex': r'$E_{\rm true}$'}
true_nutaufine.true_coszen = {'num_bins':160, 'is_lin':True, 'domain':[-1,1], 'tex':r'$\cos\,\theta_{Z,{\rm true}}$'}

true_nutau.order = true_coszen, true_energy
true_nutau.true_energy = {'num_bins':15, 'is_log':True, 'domain':[2.3,180] * units.GeV, 'tex': r'$E_{\rm true}$'}
true_nutau.true_coszen = {'num_bins':16, 'is_lin':True, 'domain':[-1,1], 'tex':r'$\cos\,\theta_{Z,{\rm true}}$'}

reco_nutau.order = reco_coszen, reco_energy
reco_nutau.reco_energy = {'num_bins':10, 'is_log':True, 'domain':[5.5,100.6] * units.GeV, 'tex': r'$E_{\rm reco}$'}
reco_nutau.reco_coszen = {'num_bins':16, 'is_lin':True, 'domain':[-1,1], 'tex':r'$\cos\,\theta_{Z,{\rm reco}}$'}

true_allskyfine.order = true_coszen, true_energy
true_allskyfine.true_energy = {'num_bins':400, 'is_log':True, 'domain':[1,80] * units.GeV, 'tex': r'$E_{\rm true}$'}
true_allskyfine.true_coszen = {'num_bins':400, 'is_lin':True, 'domain':[-1,1], 'tex':r'$\cos\,\theta_{Z,{\rm true}}$'}

true_upgoing.order = true_coszen, true_energy
true_upgoing.true_energy = {'num_bins':39, 'is_log':True, 'domain':[1,80] * units.GeV, 'tex': r'$E_{\rm true}$'}
true_upgoing.true_coszen = {'num_bins':20, 'is_lin':True, 'domain':[-1,0], 'tex':r'$\cos\,\theta_{Z,{\rm true}}$'}

true_upgoingfine.order = true_coszen, true_energy
true_upgoingfine.true_energy = {'num_bins':390, 'is_log':True, 'domain':[1,80] * units.GeV, 'tex': r'$E_{\rm true}$'}
true_upgoingfine.true_coszen = {'num_bins':200, 'is_lin':True, 'domain':[-1,0], 'tex':r'$\cos\,\theta_{Z,{\rm true}}$'}

reco_allsky.order = reco_coszen, reco_energy
reco_allsky.reco_energy = {'num_bins':40, 'is_log':True, 'domain':[1,80] * units.GeV, 'tex': r'$E_{\rm reco}$'}
reco_allsky.reco_coszen = {'num_bins':40, 'is_lin':True, 'domain':[-1,1], 'tex':r'$\cos\,\theta_{Z,{\rm reco}}$'}

reco_upgoing.order = reco_coszen, reco_energy
reco_upgoing.reco_energy = {'num_bins':39, 'is_log':True, 'domain':[1,80] * units.GeV, 'tex': r'$E_{\rm reco}$'}
reco_upgoing.reco_coszen = {'num_bins':20, 'is_lin':True, 'domain':[-1,0], 'tex':r'$\cos\,\theta_{Z,{\rm reco}}$'}

;------------------------------------------------------------------------------
; Flux
;------------------------------------------------------------------------------

[stage:mc]

; instantiation arguments
output_binning = reco_nutau

; * nu/nubar ratio
param.nu_nubar_ratio = 1.0 +/- 0.1
param.nu_nubar_ratio.fixed = True
param.nu_nubar_ratio.range = nominal + [-3., +3.] * sigma
; * nu_e/nu_mu ratio
param.nue_numu_ratio = 1.0 +/- 0.03
param.nue_numu_ratio.fixed = True
param.nue_numu_ratio.range = nominal + [-10., +10.] * sigma

param.earth_model = osc/PREM_12layer.dat

param.YeI = 0.4656
param.YeM = 0.4957
param.YeO = 0.4656

param.detector_depth = 2. units.km
param.prop_height = 20. units.km

; selects the params denoted by param.<param_selector>.<paramname>
param_selector = nh

param.theta12 = <!loi2|theta12!>
param.theta12.fixed = True

param.theta13 = <!loi2|theta13!>
param.theta13.fixed = True
param.theta13.range = nominal + [-3.25, +3] * sigma

param.nh.theta23 = <!nufit2|theta23_nh!>
param.nh.theta23.fixed = False
param.nh.theta23.range = [31, 59] * units.deg
param.nh.theta23.prior = <!nufit2|theta23_nh.prior!>
param.nh.theta23.prior.data = <!nufit2|theta23_nh.prior.data!>

param.ih.theta23 = <!nufit2|theta23_ih!>
param.ih.theta23.fixed = False
param.ih.theta23.range = [31, 59] * units.deg
param.ih.theta23.prior = <!nufit2|theta23_ih.prior!>
param.ih.theta23.prior.data = <!nufit2|theta23_ih.prior.data!>

param.deltacp = <!loi2|deltacp!>
param.deltacp.fixed = True

param.deltam21 = <!loi2|deltam21!>
param.deltam21.fixed = True

param.nh.deltam31 = <!loi2|deltam31_nh!>
param.nh.deltam31.fixed = False
param.nh.deltam31.range = nominal + [-0.16e-3, +0.54e-3] * units.eV**2

param.ih.deltam31 = <!loi2|deltam31_ih!>
param.ih.deltam31.fixed = False
param.ih.deltam31.range = nominal + [-0.13e-3, 0.47e-3] * units.eV**2

param.events_file = /fastio/peller/events__deepcore__IC86__runs_126001-126003,146001-146003,166001-166003__proc_v5digit__unjoined_with_fluxes_GENIE_Barr.hdf5 

param.livetime = 4. units.julian_year

param.aeff_scale = 1. +/- 0.1
param.aeff_scale.fixed = False
param.aeff_scale.range = nominal + [-0.3, +0.3]

param.pid_bound = 2.0
param.pid_remove = -3.0

[stage:sys]

input_binning = <!stage:pid|output_binning!>
output_binning = <!stage:sys|input_binning!>

param.dom_eff = 1.0 +/- 0.1
param.dom_eff.fixed = False
param.dom_eff.range = [0.88, 1.12] * units.dimensionless

;param.dom_eff_file = /Users/peller/PSU/cake/dom_eff_sysfits_raw.json
param.dom_eff_file = /Users/peller/PSU/cake/dom_eff_sysfits_gauss.json

param.hole_ice = 25 +/- 5.0
param.hole_ice.fixed = False
param.hole_ice.range = [15, 35]* units.dimensionless

;param.hole_ice_file = /Users/peller/PSU/cake/hole_ice_sysfits_raw.json
param.hole_ice_file = /Users/peller/PSU/cake/hole_ice_sysfits_gauss.json

param.hole_ice_fwd = 0.0 +/- 1.0
param.hole_ice_fwd.fixed = False
param.hole_ice_fwd.range = [-5.0, 2.0]* units.dimensionless

;param.hole_ice_fwd_file = /Users/peller/PSU/cake/hole_ice_fwd_sysfits_raw.json
param.hole_ice_fwd_file = /Users/peller/PSU/cake/hole_ice_fwd_sysfits_gauss.json
;------------------------------------------------------------------------------
; Define names for common things to use in the above
;------------------------------------------------------------------------------

[loi2]
; Atmospheric mixing parameters used for PINGU LoI v2.0
theta12 = 33.5 units.deg
theta12.fixed = True

theta13 = 8.5 +/- 0.2 units.deg
theta13.fixed = False

theta23_nh = 42.3 units.deg
theta23_nh.fixed = False
theta23_nh.prior = uniform

theta23_ih = 49.5 units.deg
theta23_ih.fixed = False
theta23_ih.prior = uniform

deltacp = 0 units.deg
deltacp.fixed = True

deltam21 = 7.5e-5 units.eV**2
deltam21.fixed = True

deltam31_nh = 2.46e-3 units.eV**2
deltam31_nh.fixed = False
deltam31_nh.prior = uniform

deltam31_ih = -2.37e-3 units.eV**2
deltam31_ih.fixed = False
deltam31_ih.prior = uniform

[nufit2]
; Atmospheric mixing parameters found in NuFIT 2.0
theta12 = 33.48 units.deg
theta12.prior = spline
theta12.prior.data = priors/nufit2.json

theta13_nh = 8.5 units.deg
theta13_nh.prior = spline
theta13_nh.prior.data = priors/nufit2.json

theta13_ih = 8.51 units.deg
theta13_ih.prior = spline
theta13_ih.prior.data = priors/nufit2.json

theta23_nh = 42.3 units.deg
theta23_nh.prior = spline
theta23_nh.prior.data = priors/nufit2.json

theta23_ih = 49.5 units.deg
theta23_ih.prior = spline
theta23_ih.prior.data = priors/nufit2.json

deltacp_nh = 306 units.deg
deltacp_nh.prior = spline
deltacp_nh.prior.data = priors/nufit2.json

deltacp_ih = 254 units.deg
deltacp_ih.prior = spline
deltacp_ih.prior.data = priors/nufit2.json

deltam21 = 7.5e-5 units.eV**2
deltam21.prior = spline
deltam21.prior.data = priors/nufit2.json

deltam31_nh = 0.002457 units.eV**2
deltam31_nh.prior = spline
deltam31_nh.prior.data = priors/nufit2.json

deltam31_ih = -0.002449 units.eV**2
deltam31_ih.prior = spline
deltam31_ih.prior.data = priors/nufit2.json
